title: Pagarmangkok
baseURL: /
params:
  accent_color: pink
  color_scheme: dark
  footer:
    content: '&copy; Pagarmangkok. All rights reserved'
    has_social: true
    links:
      - new_window: true
        text: ''
        url: ''
  header:
    has_nav: true
    logo_img: ''
    title: Pagarmangkok
disableKinds:
  - RSS
