title: Pagarmangkok
baseURL: /
params:
  accent_color: blue
  color_scheme: light
  footer:
    content: '&copy; Pagarmangkok. All rights reserved'
    has_social: true
    links:
      - new_window: true
        text: ''
        url: ''
  header:
    has_nav: true
    logo_img: /images/pagarmangkok_hearder.png
    title: Pagarmangkok
disableKinds:
  - RSS
